# FIXME: define a frontend & backend network, and only expose backend services to the frontend (nginx)

networks:
  matrix-net:
    internal: true
  pg-net:
    external: true
  caddy-net:
    external: true

secrets:
  pg_synapse_password:
    file: /opt/secrets/postgres/synapse_password
  pg_mas_password:
    file: /opt/secrets/postgres/mas_password
  synapse_signing_key:
    file: /opt/secrets/synapse/signing.key

services:
  # XXX: consider factor out secret generation from the compose.yml

  # dependencies for optionally generating default configs + secrets
  generate-synapse-secrets:
    image: ghcr.io/element-hq/synapse:${SYNAPSE_VERSION}
    user: $USER_ID:$GROUP_ID
    restart: "no"
    volumes:
      - ${VOLUME_PATH}/data/synapse:/data:rw
      - ${VOLUME_PATH}/scripts/generate-synapse-secrets.sh:/entrypoint.sh
    env_file: .env
    environment:
      SYNAPSE_CONFIG_DIR: /data
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml.default
      SYNAPSE_SERVER_NAME: ${DOMAIN}
      SYNAPSE_REPORT_STATS: ${REPORT_STATS}
    entrypoint: "/entrypoint.sh"

  generate-mas-secrets:
    restart: "no"
    build: 
      context: containers/mas-init
      args:
        MAS_VERSION: ${MAS_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
    env_file: .env
    user: $USER_ID:$GROUP_ID
    volumes:
      - ${VOLUME_PATH}/data/mas:/data:rw
      - ${VOLUME_PATH}/scripts/generate-mas-secrets.sh:/start.sh
    command: "/start.sh"
  # dependency for templating /data-template into /data (having extracted any secrets from any default generated configs)
  init:
    build: 
      context: containers/init
      args:
        MAS_VERSION: ${MAS_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
    user: $USER_ID:$GROUP_ID
    restart: "no"
    volumes:
      - /opt/secrets/mas:/secrets/mas:rw
      - /opt/secrets/synapse:/secrets/synapse:rw
      - ${VOLUME_PATH}/data:/data
      - ${VOLUME_PATH}/data-template:/data-template
      - ${VOLUME_PATH}/scripts/init.sh:/init.sh
    command: "/init.sh"
    secrets:
      - pg_synapse_password
      - pg_mas_password
    env_file: .env
    depends_on:
      generate-synapse-secrets:
        condition: service_completed_successfully
      generate-mas-secrets:
        condition: service_completed_successfully

  nginx:
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    #ports:
    #  - "80:80"
    #  - "8448:8448"
    # shutdown fast so we can iterate rapidly on compose.yml
    stop_grace_period: 0s
    volumes:
      - ${VOLUME_PATH}/data/nginx/conf.d:/etc/nginx/conf.d
      - ${VOLUME_PATH}/data/nginx/www:/var/www
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      caddy-net:
      matrix-net:
        aliases: # so our containers can resolve the LB
          - $DOMAIN
          - $HOMESERVER_FQDN
          - $ELEMENT_WEB_FQDN
          - $ELEMENT_CALL_FQDN
          - $MAS_FQDN
    depends_on:
      init:
        condition: service_completed_successfully

  synapse:
    build: 
      context: containers/synapse
      args:
        SYNAPSE_VERSION: ${SYNAPSE_VERSION}
    user: $USER_ID:$GROUP_ID
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/data/synapse:/data:rw
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8008/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    # ports:
    #   - 8008:8008
    networks:
      - matrix-net
      - pg-net
    environment:
      SYNAPSE_CONFIG_DIR: /data
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    secrets:
      - synapse_signing_key
    depends_on:
      #postgres:
      #  condition: service_healthy
      init:
        condition: service_completed_successfully

  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:${MAS_VERSION}
    restart: unless-stopped
    # ports:
    #   - 8083:8080
    volumes:
      - ${VOLUME_PATH}/data/mas:/data:rw
    networks:
      - matrix-net
      - pg-net
    # FIXME: do we also need to sync the db?
    command: "server --config=/data/config.yaml"
    depends_on:
      #postgres:
      #  condition: service_healthy
      init:
        condition: service_completed_successfully

  element-web:
    image: vectorim/element-web:${WEB_VERSION}
    restart: unless-stopped
    # ports:
    #   - 8080:80
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80/version || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix-net
    volumes:
      - ${VOLUME_PATH}/data/element-web/config.json:/app/config.json
    depends_on:
      init:
        condition: service_completed_successfully

  # Element Admin - Web UI for managing users/rooms via MAS
  element-admin:
    build: containers/element-admin
    # container_name: matrix-element-admin
    restart: unless-stopped
    environment:
      SERVER_NAME: $DOMAIN
    networks:
      - matrix-net
    depends_on:
      - synapse
      - mas